# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-node:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout step
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Packages        
      run: |
        npm install
    - name: Run vitests
      run: |
        npm run test:unit
    - name: Run the data server
      run: |
        docker run -d --name datastore -p 3000:80 -v ${{ github.workspace }}/data/db.json:/data/db.json clue/json-server
        sleep 5
    - name: Check the data server        
      run: curl -vvvv http://localhost:3000/students
    - name: Run cypress  tests
      uses: cypress-io/github-action@v5
      with:  
        build: npm run build
        start: npm run dev      
        browser: firefox
    - name: Upload cypress files
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        path: |
          cypress/videos
          cypress/screenshots